# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

queue:

  name: Hosted Ubuntu 1604

steps:

- task: ArchiveFiles@1

  displayName: 'Archive files'

  inputs:

    rootFolder: '$(System.DefaultWorkingDirectory)'



    includeRootFolder: false



    archiveType: zip





- task: CopyFiles@2

  displayName: 'Copy ARM templates'

  inputs:

    SourceFolder: ArmTemplates



    TargetFolder: '$(build.artifactstagingdirectory)'





- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'