# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: sudo apt-get install libmysqlclient-dev
  displayName: 'install MySql-client'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4 --path vendor/bundle
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
