# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

# queue:
#  name: Hosted Ubuntu 1604

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
- group: MDLive-ProdVar

name: $(Date:yyyyMMdd)$(Rev:.r)

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true

- script: sudo apt-get update
  displayName: 'Update packages'

- script: sudo apt-get install libmysqlclient-dev
  displayName: 'Install MySql client'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4 --path vendor/bundle
  displayName: 'Bundle install'

- script: gem install rails && rails -v
  displayName: 'Install rails gem'

- bash: echo $DB-HOST
  displayName: 'Set environment variables for rake'
  failOnStderr: true
  env: 
    DB-HOST: $(DB-HOST)
    DB-DATABASE: $(DB-DATABASE)
    DB-USERNAME: $(DB-USERNAME)
    DB-PASSWORD: $(DB-PASSWORD)

- script: bundle exec rake db:migrate RAILS_ENV=production
  displayName: 'Run rake to migrate db and set environment'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'